#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d . . . . . . .

bspc config border_width 1

bspc config left_padding  45
bspc config right_padding 45
bspc config top_padding   1
bspc config window_gap 15

# Monocle
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config left_monocle_padding   10
bspc config right_monocle_padding  10
bspc config top_monocle_padding    11
bspc config bottom_monocle_padding 10

bspc config split_ratio          0.69
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium        desktop='^1'
bspc rule -a firefox         desktop='^1'
bspc rule -a Emacs           desktop='^3' state="tiled"
bspc rule -a TelegramDesktop desktop='^4' state="tiled"

polybar &
feh --bg-scale ~/.config/wallpapers/space.jpg
