#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 1

bspc config left_padding  60
bspc config right_padding 60
bspc config top_padding   3
bspc config window_gap    20

# Monocle
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config left_monocle_padding   70
bspc config right_monocle_padding  70
bspc config top_monocle_padding    13
bspc config bottom_monocle_padding 13

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium        desktop='^1'
bspc rule -a firefox         desktop='^1'
bspc rule -a Emacs           state="tiled"
bspc rule -a TelegramDesktop desktop='^4' state="tiled"

# 400ms - time before pressing one character enable repetition
# 45 - amount of presses will be processed per second while repetition
#   is enabled
xset r rate 400 33

polybar &
feh --bg-scale ~/.config/wallpapers/ph.jpg
